### ISSUE TITLE
-r / --recon exports to HBD .yuv even when encoding to 8-bit

### ISSUE THREAD

**Issue by motbob** [mpeg5/xeve#10]
Tested on master (28c76a25eb9520f93fe101f26981b4cf3704802d)

Input: 267MB 8-bit 4:2:0 raw video.

Command line: `xeve/build/bin/xeveb_app -i heya.yuv -w 1920 -h 1080 -m 16 -r placebo.yuv -z 24 -I 3200 -q 16 --preset placebo --closed_gop -o evc.bin`

Expectation: placebo.yuv should be a 267MB raw video file with 8-bit pixels, like the input file.  
Actual result: placebo.yuv is a 534MB HBD raw video file.

**Comment by mpeg5** [comment]
can you try to display the reconstructed video with 10bit yuv420 format?
I remember that EVC uses the internal bit depth  increment tool.

**Comment by motbob** [comment]
> 
> 
> can you try to display the reconstructed video with 10bit yuv420 format?
> I remember that EVC uses the internal bit depth increment tool.

Yes, the output is raw video that is read properly in ffmpeg with -pix_fmt yuv420p10le.

I expected the output of -r to be the same as if you ran the encoded output through a decoder and exported to yuv. Is that a wrong expectation?

**Comment by mpeg5** [comment]
-r option is for debugging only. Basically, the option don't have to be used for actual operation.
The last 2 bits is actual data, not fake.
But, we can remove the last 2bits if yuv420 8bit is required.

**Comment by motbob** [comment]
It's not required. I was reporting this because I assumed it was unintentional. I'll close now that I know it's not a bug.

FWIW, since there is no public decoder, I was using -r so that I could have something that I could actually decode. It's fine to have 10-bit raw video for that purpose since the user can downscale to 8-bit themselves.
