### ISSUE TITLE
libxeve 0.5.1 tag build error with ffmpeg 7.0.1

### ISSUE THREAD

**Issue by wader** [mpeg5/xeve#120]
Not sure if 0.5.1 has been released yet but an automated update build triggered on the new tag failed with this:
```
...
libavcodec/libxeve.c:199:27: error: incompatible types when assigning to type 'XEVE_RATIONAL' {aka 'struct _XEVE_RATIONAL'} from type 'long int'
  199 |         cdsc->param.fps = lrintf(av_q2d(avctx->framerate));
      |                           ^~~~~~
libavcodec/libxeve.c: In function 'libxeve_encode':
libavcodec/libxeve.c:484:40: error: incompatible types when assigning to type 'int' from type 'XEVE_RATIONAL' {aka 'struct _XEVE_RATIONAL'}
  484 |                 avpkt->time_base.den = xectx->cdsc.param.fps;
      |                                        ^~~~~
```

**Comment by dariusz-f** [comment]
Yes, API was changed and need to be updated on FFmpeg side. Soon we will prepare patch.

**Comment by wader** [comment]
👍 close issue or let it be open until patch has been merged?

**Comment by dariusz-f** [comment]
Problem exists, so keep issue opened.

**Comment by dkozinski** [comment]
> Not sure if 0.5.1 has been released yet but an automated update build triggered on the new tag failed with this:
> 
> ```
> ...
> libavcodec/libxeve.c:199:27: error: incompatible types when assigning to type 'XEVE_RATIONAL' {aka 'struct _XEVE_RATIONAL'} from type 'long int'
>   199 |         cdsc->param.fps = lrintf(av_q2d(avctx->framerate));
>       |                           ^~~~~~
> libavcodec/libxeve.c: In function 'libxeve_encode':
> libavcodec/libxeve.c:484:40: error: incompatible types when assigning to type 'int' from type 'XEVE_RATIONAL' {aka 'struct _XEVE_RATIONAL'}
>   484 |                 avpkt->time_base.den = xectx->cdsc.param.fps;
>       |                                        ^~~~~
> ```

I've just submitted a patch to the FFmpeg project that fixes the problem.

https://patchwork.ffmpeg.org/project/ffmpeg/patch/20240625122016.862-1-d.kozinski@samsung.com/

**Comment by dkozinski** [comment]
The patch has just been merged

**Comment by dariusz-f** [comment]
Need to test and confirm this with latest FFmpeg HEAD. After sucessfull test we can close this issue.

**Comment by dkozinski** [comment]
Checked. It works with latest ffmpeg.
