### ISSUE TITLE
xeve_app returns 205 exit code on encoding successful

### ISSUE THREAD

**Issue by olokelo** [mpeg5/xeve#137]
Hello,

When `xeve_app` finishes encoding it exits with status 205 which [means](https://github.com/mpeg5/xeve/blob/954ed6e0494cd2438fd15c717c0146e88e582b33/inc/xeve.h#L50C9-L50C28) `XEVE_OK_NO_MORE_FRM`. Is it expected behavior?
I know that encoding was OK but shouldn't the app exit with code 0 on success? That would conform with the Unix Standard.

```shell
$ xeve_app -i dnd.y4m -q 38 --keyint 128 --profile main --preset fast --threads 8 -o dnd.xeve-evc_main_fast_g128_q38.evc
XEVE: eXtra-fast Essential Video Encoder
=== Summary ====================================================================
Bitrate                           = 268.7698 kbps
Encoded frame count               = 276
Total encoding time               = 367019.000 msec, 367.019 sec
Average encoding time for a frame = 1329.779 msec
Average encoding speed            = 0.752 frames/sec
================================================================================
[oloke@pc tmp]$ echo $?
205
```

**Comment by kpchoi** [comment]
@dariusz-f 
I guess that xeve_app should not return xeve libraries' return value.
XEVE_OK_NO_MORE_FRM is libxeve return value and it means that encoding was ok.
in that case, xeve_app should return 0.
