### ISSUE TITLE
[Feature Request] Support y4m piping

### ISSUE THREAD

**Issue by master-of-zen** [mpeg5/xeve#2]
Please add support for y4m input, and piping support.
Thanks :)

**Comment by mpeg5** [comment]
@master-of-zen 
You can test Y4M file as a input of xeve encoder for now (with master branch)
If no more issue about this, I will close this thread soon.

**Comment by master-of-zen** [comment]
y4m input doesn't work for me
```
> xeveb_app -i scene_check.y4m 
eXtra-fast Essential Video Encoder
[xeve_app.c:942] Error parsing header; not a YUV2MPEG2 file?
[xeve_app.c:1086] This y4m is not supported (scene_check.y4m)```

**Comment by mpeg5** [comment]
I'm not sure your scene_check.y4m is following Y4M file format. try to check it.

**Comment by mpeg5** [comment]
@master-of-zen 

Again, could you share the y4m file what you tested before?
Or, you can dump the file at beginning part and past the captured image of it.

**Comment by mpeg5** [comment]
@master-of-zen 

Hi, we added default color space value if the y4m file doesn't have the information in header.
Could you check "scene_check.y4m" file again?

**Comment by mpeg5** [comment]
Recently, there was a code improvement for y4m reading in case of missing syntax in header.
And, there is no comments after July.
So, I'd like to close this issue for now.
Let's open this issue if needs.
