### ISSUE TITLE
Metadata and SEI/VUI messages

### ISSUE THREAD

**Issue by zhguyu** [mpeg5/xeve#25]
At the moment the encoder doesn't seem to write metadata or SEI/VUI messages into the output stream. This can make it harder for users to inspect the output using programs like Mediainfo, and video players like PotPlayer rely on those messages to properly decode the stream (although I suppose decoding EVC isn't supported for the time being anyway).
I wonder if it will become a feature in the future?

**Comment by zhguyu** [comment]
I think what I want to ask is the metadata in general, plus the possibility to specify SEI messages from the command line options.

**Comment by mpeg5** [comment]
It seems to be valuable information.
We could prepare the similar functinality soon even though it is not normative part.

**Comment by kpchoi** [comment]
Hi, @zhguyu 
Your requests are implemented in this PR https://github.com/mpeg5/xeve/pull/42
and it is merged to master.
You could check the code and let us know if you find something issue more.
