### ISSUE TITLE
xeve_tbl_satd_16b_neon cannot be found.

### ISSUE THREAD

**Issue by khjj07** [mpeg5/xeve#63]
Unable to build project on Raspberrypi4.
It seems that the module xeve_tbl_satd_16b_neon cannot be found.

Error message : 

xeve/src_base/xeve_enc.c:720:39: error: ‘xeve_tbl_satd_16b_neon’ undeclared (first use in this function); did you mean ‘xeve_tbl_sad_16b_neon’?
  720 |         xeve_func_satd              = xeve_tbl_satd_16b_neon;
      |                                       ^~~~~~~~~~~~~~~~~~~~~~
      |                                       xeve_tbl_sad_16b_neon
/home/pi/Desktop/original/xeve/src_base/xeve_enc.c:720:39: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [src_base/CMakeFiles/xeveb_dynamic.dir/build.make:134: src_base/CMakeFiles/xeveb_dynamic.dir/xeve_enc.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:164: src_base/CMakeFiles/xeveb_dynamic.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

**Comment by mpeg5** [comment]
Added the file.
Could you test again?

**Comment by khjj07** [comment]
This error no longer occurs.
