### ISSUE TITLE
Another Error occur while link process

### ISSUE THREAD

**Issue by khjj07** [mpeg5/xeve#65]
I cannot execute 'make' command in Raspberry Pi 4. 
Error message : 
[ 97%] Linking C executable ../bin/xeveb_app
/usr/bin/ld: attempted static link of dynamic object `../lib/libxeveb.so.0.4'
collect2: error: ld returned 1 exit status
make[2]: *** [app/CMakeFiles/xeveb_app.dir/build.make:104: bin/xeveb_app] Error 1
make[1]: *** [CMakeFiles/Makefile2:218: app/CMakeFiles/xeveb_app.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

**Comment by kpchoi** [comment]
@mamthan 

Hi, could you check this issue also?

**Comment by mamthan** [comment]
@khjj07 @kpchoi 
Thank you for reporting the issue. 
We have fixed the build errors, and checked it into the branch (https://github.com/mpeg5/xeve/tree/xeve_build_error_fix). 
It is currently pending on the merge to the master #66 .

Please test this and let us know your comments.

**Comment by khjj07** [comment]
@mamthan
The problem has been fixed and the build works fine
