### ISSUE TITLE
Noticeable fluctuation in quality between frames

### ISSUE THREAD

**Issue by motbob** [mpeg5/xeve#7]
I encoded the following sample with xeve (baseline) at q16: https://0x0.st/-afA.mkv

At q16, I would expect all frames to look pretty good. But xeve's output varied significantly between frames. For some frames, all the fine detail in the original was preserved. But in other frames, the picture was smudged and/or blocky.

`xeve/build/bin/xeveb_app -i input.yuv -w 1920 -h 1080 -m 16 -r evc.yuv -z 24 -p 3200 -q 16 --preset medium -o evc.bin`

I made a comparison showing the VMAF scores by frame to illustrate, compared against a crf 21 x264 encode. 

![](https://i.gyazo.com/2f65018d1e3da812178b8248b8cc88d9.png)

EDIT, 2021-05-18: The command line above is now outdated, you need to use -I (capital i) instead of -p.

**Comment by mpeg5** [comment]
Hi, @motbob,
Have you tried to use --preset placebo instead of medium?

**Comment by motbob** [comment]
![](https://i.gyazo.com/42013ce84761027dbec1b9ff7826795f.png)

Yes, that fixed the problem, though I think it's weird that changing a speed preset should have such a large impact on quality. In other encoders, I expect speed presets to impact filesize, not quality.

However, if the encoder is working as intended, feel free to close this issue. I guess I will stick with `--preset reference` when encoding with good q.

**Comment by mpeg5** [comment]
@motbob 

Hi, could you test again with the latest master branch?
We improved coding gain without quality difference between presets.

**Comment by motbob** [comment]
![](https://i.gyazo.com/329dce4ca0f9ddc364a6dcb2c4f262c2.png)

Looks like the issue is fixed. I guess that new bitrate drop at the end is due to cutree?
