### ISSUE TITLE
Prepare API documentation

### ISSUE THREAD

**Issue by dariusz-f** [mpeg5/xeve#75]
Xeve public API should be well documented, then it will be easier to use.
For below functions it will be good to provide comprehensive documentation. 

https://github.com/mpeg5/xeve/blob/1afa591020ce13b0c122a38c4b10d4937448205b/inc/xeve.h#L588-L596

Doxygen format in my opinion should be preferred because it is well integrated with multiple IDEs and it's a standard way to document code.

Let's discuss how it should be documented and in next step we will prepare PR with documentation.

**Comment by kpchoi** [comment]
I think it would be valuable.
Let's start to add API documentation.
