### ISSUE TITLE
Question - Participate in MSU Video Codecs Comparison 2021?

### ISSUE THREAD

**Issue by ontran** [mpeg5/xeve#8]
This is a question rather than an issue.

Will be interested to see another 3rd party eval of EVC vs other boys. MSU is calling for codecs. Thanks.

**Comment by mpeg5** [comment]
I'm not sure that the current implementation is well enough to participate to video codec comparison.
I believe that we need much more contributions to make better compression gain and speed-up of xeve. :-)
Hey, contributors, do you have any opinion of this?
