### ISSUE TITLE
How to decode a video?

### ISSUE THREAD

**Issue by Jamaika1** [mpeg5/xeve#9]
How to decode a video?
https://www.sendspace.com/file/gstvge

**Comment by mpeg5** [comment]
You could use EVC reference software.
But we're going to create a decoder project also soon. You could use it for decoding of bitstream.

**Comment by mpeg5** [comment]
@Jamaika1 
Hi, now EVC decoder project has launched.
You can use https://github.com/mpeg5/xevd for testing xeve encoder, now.

**Comment by Jamaika1** [comment]
Thanks, :)
