### ISSUE TITLE
v1.0.0 release?

### ISSUE THREAD

**Issue by Selur** [mpeg5/xeve#95]
The README.md states
```
    Baseline Profile:
        xeve-base-1.0.0-win64.exe
        xeve-base-1.0.0-win64.exe.md5

    Main Profile:
        xeve-main-1.0.0-win64.exe
        xeve-main-1.0.0-win64.exe.md5
```
but the latest release is 0.4.3.
=> is the README wrong, are newer builds not public anymore?

**Comment by dariusz-f** [comment]
Latest version is that in release section. In readme it's just example.

**Comment by Selur** [comment]
Thanks for clearing that up.
